'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { root, yaml, readYaml } = require('./lib/project.cjs');

// Obvious token shapes. This is a last-resort guard for the committed recovery
// template, not a general secret scanner.
const SUSPECT_VALUE = /(ghp_[A-Za-z0-9]{16,}|github_pat_[A-Za-z0-9_]{16,}|AKIA[0-9A-Z]{12,}|sk-[A-Za-z0-9]{20,}|-----BEGIN [A-Z ]*PRIVATE KEY)/;

function isCredentialKey(key) {
  return /secret|secred|password|token|private.?key|api.?key|access.?key/i.test(key)
    || /^(client_?id|app_?id|app_?key)$/i.test(key);
}

function isPlainObject(value) {
  if (value === null || typeof value !== 'object') return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function sanitize(value) {
  if (Array.isArray(value)) return value.map(sanitize);
  // Dates and other non-plain objects must survive unchanged; recursing would
  // silently turn them into "{}".
  if (!isPlainObject(value)) return value;
  const result = {};
  for (const [key, item] of Object.entries(value)) {
    result[key] = isCredentialKey(key) ? '' : sanitize(item);
  }
  return result;
}

function suspectPaths(value, trail = '', found = []) {
  if (typeof value === 'string') {
    if (SUSPECT_VALUE.test(value)) found.push(trail || '(root)');
  } else if (Array.isArray(value)) {
    value.forEach((item, index) => suspectPaths(item, `${trail}[${index}]`, found));
  } else if (isPlainObject(value)) {
    for (const [key, item] of Object.entries(value)) suspectPaths(item, trail ? `${trail}.${key}` : key, found);
  }
  return found;
}

function exampleText(config) {
  return '# Generated by npm run config:example from local settings.\n'
    + '# Credential-like fields are deliberately blank. Review before committing.\n'
    + '# npm run setup copies this file only if _config.Butterfly.yml is absent.\n'
    + yaml.dump(sanitize(config), { noRefs: true, lineWidth: 120, sortKeys: false });
}

if (require.main === module) {
  try {
    const destination = path.join(root, 'config/butterfly.example.yml');
    if (process.argv[2] !== '--write') throw new Error('Use npm run config:example -- --write to explicitly refresh the sanitized snapshot.');
    const source = readYaml(path.join(root, '_config.Butterfly.yml'));
    const sanitized = sanitize(source);
    const suspects = suspectPaths(sanitized);
    if (suspects.length) {
      // Refuse rather than publish a token-shaped value into a versioned file.
      throw new Error(`Refusing to write: token-shaped value(s) at ${suspects.join(', ')}. Rename or clear them first.`);
    }
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, exampleText(source), 'utf8');
    console.log('Wrote config/butterfly.example.yml (credential fields blank; local settings unchanged).');
  } catch (error) {
    console.error(error.message); process.exitCode = 1;
  }
}
module.exports = { isCredentialKey, isPlainObject, sanitize, suspectPaths, exampleText };
